# Generated by Django 6.0.4 on 2026-04-27 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        ("operations", "0002_add_ground_log_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Breeding/mating date")),
                (
                    "method",
                    models.CharField(
                        choices=[("NATURAL", "Natural"), ("ASSISTED", "Assisted")],
                        default="NATURAL",
                        help_text="Breeding method",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_sire",
                    models.CharField(
                        choices=[
                            ("SIRE1", "Sire 1"),
                            ("SIRE2", "Sire 2"),
                            ("UNCONFIRMED", "Unconfirmed"),
                        ],
                        default="UNCONFIRMED",
                        help_text="Which sire was confirmed as the father",
                        max_length=20,
                    ),
                ),
                (
                    "expected_whelp_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected whelping date (breeding date + 63 days)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_breedings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        help_text="Female parent",
                        limit_choices_to={"gender": "F"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dam_breedings",
                        to="operations.dog",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breeding_records",
                        to="core.entity",
                    ),
                ),
                (
                    "sire1",
                    models.ForeignKey(
                        help_text="Primary male parent",
                        limit_choices_to={"gender": "M"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire1_breedings",
                        to="operations.dog",
                    ),
                ),
                (
                    "sire2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secondary male parent (dual-sire breeding)",
                        limit_choices_to={"gender": "M"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire2_breedings",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "breeding_records",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DogClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        help_text="Generations between ancestor and descendant",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ancestor",
                    models.ForeignKey(
                        help_text="Ancestor dog",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendant_paths",
                        to="operations.dog",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        help_text="Descendant dog",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_paths",
                        to="operations.dog",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_entries",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "dog_closure",
                "ordering": ["ancestor", "descendant"],
            },
        ),
        migrations.CreateModel(
            name="Litter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("whelp_date", models.DateField(help_text="Actual whelping date")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("NATURAL", "Natural"), ("C_SECTION", "C-Section")],
                        default="NATURAL",
                        help_text="Delivery method",
                        max_length=20,
                    ),
                ),
                (
                    "alive_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of puppies born alive",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "stillborn_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of stillborn puppies",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total puppies (alive + stillborn)"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Delivery notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breeding_record",
                    models.OneToOneField(
                        help_text="Associated breeding record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="litter",
                        to="breeding.breedingrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_litters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="litters",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "litters",
                "ordering": ["-whelp_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MateCheckOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "coi_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated COI percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "saturation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated farm saturation percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("SAFE", "Safe"),
                            ("CAUTION", "Caution"),
                            ("HIGH_RISK", "High Risk"),
                        ],
                        help_text="System-calculated verdict",
                        max_length=20,
                    ),
                ),
                (
                    "override_reason",
                    models.CharField(
                        help_text="Reason for overriding the verdict", max_length=200
                    ),
                ),
                (
                    "override_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the override"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dam",
                    models.ForeignKey(
                        limit_choices_to={"gender": "F"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dam_override_checks",
                        to="operations.dog",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mate_check_overrides",
                        to="core.entity",
                    ),
                ),
                (
                    "sire1",
                    models.ForeignKey(
                        limit_choices_to={"gender": "M"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire1_override_checks",
                        to="operations.dog",
                    ),
                ),
                (
                    "sire2",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gender": "M"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire2_override_checks",
                        to="operations.dog",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mate_check_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mate_check_overrides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Puppy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "microchip",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Microchip number (assigned later)",
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="Puppy gender",
                        max_length=1,
                    ),
                ),
                (
                    "colour",
                    models.CharField(help_text="Coat color/markings", max_length=50),
                ),
                (
                    "birth_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Birth weight in grams",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "confirmed_sire",
                    models.CharField(
                        choices=[
                            ("SIRE1", "Sire 1"),
                            ("SIRE2", "Sire 2"),
                            ("UNCONFIRMED", "Unconfirmed"),
                        ],
                        default="UNCONFIRMED",
                        help_text="Which sire is the confirmed father",
                        max_length=20,
                    ),
                ),
                (
                    "paternity_method",
                    models.CharField(
                        choices=[
                            ("VISUAL", "Visual Assessment"),
                            ("DNA", "DNA Test"),
                            ("UNCONFIRMED", "Unconfirmed"),
                        ],
                        default="UNCONFIRMED",
                        help_text="Method used to determine paternity",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ALIVE", "Alive"),
                            ("REHOMED", "Rehomed"),
                            ("DECEASED", "Deceased"),
                        ],
                        default="ALIVE",
                        help_text="Current puppy status",
                        max_length=20,
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        blank=True, help_text="Buyer's name", max_length=100
                    ),
                ),
                (
                    "buyer_contact",
                    models.CharField(
                        blank=True, help_text="Buyer's contact", max_length=100
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(
                        blank=True, help_text="Date of sale/rehoming", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puppies",
                        to="core.entity",
                    ),
                ),
                (
                    "litter",
                    models.ForeignKey(
                        help_text="Litter this puppy belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puppies",
                        to="breeding.litter",
                    ),
                ),
            ],
            options={
                "db_table": "puppies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["dam", "date"], name="breeding_re_dam_id_c2b5d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["sire1", "date"], name="breeding_re_sire1_i_cc984e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["entity", "date"], name="breeding_re_entity__d5925a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="breedingrecord",
            index=models.Index(
                fields=["created_at"], name="breeding_re_created_872949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dogclosure",
            index=models.Index(
                fields=["ancestor", "descendant", "depth"],
                name="dog_closure_ancesto_1670e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dogclosure",
            index=models.Index(
                fields=["entity", "ancestor"], name="dog_closure_entity__34f1e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dogclosure",
            index=models.Index(
                fields=["entity", "descendant"], name="dog_closure_entity__193fda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dogclosure",
            index=models.Index(fields=["depth"], name="dog_closure_depth_4993cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dogclosure",
            unique_together={("ancestor", "descendant")},
        ),
        migrations.AddIndex(
            model_name="litter",
            index=models.Index(
                fields=["entity", "whelp_date"], name="litters_entity__fe312b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="litter",
            index=models.Index(
                fields=["breeding_record"], name="litters_breedin_7e9264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="litter",
            index=models.Index(
                fields=["created_at"], name="litters_created_9ea2fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matecheckoverride",
            index=models.Index(
                fields=["entity", "created_at"], name="mate_check__entity__4e94c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matecheckoverride",
            index=models.Index(
                fields=["dam", "sire1", "created_at"],
                name="mate_check__dam_id_f417bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matecheckoverride",
            index=models.Index(
                fields=["staff", "created_at"], name="mate_check__staff_i_e1a50b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puppy",
            index=models.Index(
                fields=["litter", "gender"], name="puppies_litter__dffcd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puppy",
            index=models.Index(
                fields=["entity", "status"], name="puppies_entity__4c0be8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puppy",
            index=models.Index(fields=["microchip"], name="puppies_microch_a29b9d_idx"),
        ),
        migrations.AddIndex(
            model_name="puppy",
            index=models.Index(
                fields=["created_at"], name="puppies_created_73189d_idx"
            ),
        ),
    ]
