# Generated by Django 6.0.4 on 2026-05-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puppy",
            name="buyer_contact",
        ),
        migrations.RemoveField(
            model_name="puppy",
            name="buyer_name",
        ),
    ]
