# Generated by Django 6.0.4 on 2026-05-06 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0002_remove_puppy_buyer_fields"),
        ("core", "0003_change_dogclosure_entity_to_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dogclosure",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closure_entries",
                to="core.entity",
            ),
        ),
    ]
