# Generated by Django 6.0.4 on 2026-04-26 03:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "microchip",
                    models.CharField(
                        db_index=True,
                        help_text="Unique microchip number (9-15 digits)",
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("dob", models.DateField(help_text="Date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                            ("REHOMED", "Rehomed"),
                            ("DECEASED", "Deceased"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "dna_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("RESULTS_RECEIVED", "Results Received"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("dna_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dogs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mother",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dam_offspring",
                        to="operations.dog",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dogs",
                        to="core.entity",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        help_text="Father",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire_offspring",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "dogs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DogPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROFILE", "Profile"),
                            ("HEALTH", "Health"),
                            ("BREEDING", "Breeding"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "customer_visible",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this photo is visible to customers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="operations.dog",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dog_photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VET_VISIT", "Vet Visit"),
                            ("TREATMENT", "Treatment"),
                            ("OBSERVATION", "Observation"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperature in Celsius",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("vet_name", models.CharField(blank=True, max_length=100)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "health_records",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("date_given", models.DateField()),
                ("vet_name", models.CharField(blank=True, max_length=100)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP_TO_DATE", "Up to Date"),
                            ("DUE_SOON", "Due Soon"),
                            ("OVERDUE", "Overdue"),
                        ],
                        db_index=True,
                        default="UP_TO_DATE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccinations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "vaccinations",
                "ordering": ["-date_given"],
            },
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(
                fields=["entity", "status"], name="dogs_entity__238d46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(
                fields=["entity", "breed"], name="dogs_entity__d04050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["dob"], name="dogs_dob_c09cb4_idx"),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["unit"], name="dogs_unit_397d29_idx"),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["microchip"], name="dogs_microch_ef7dce_idx"),
        ),
        migrations.AddIndex(
            model_name="healthrecord",
            index=models.Index(
                fields=["dog", "date"], name="health_reco_dog_id_6ea4df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccination",
            index=models.Index(
                fields=["dog", "status"], name="vaccination_dog_id_e09924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccination",
            index=models.Index(
                fields=["due_date"], name="vaccination_due_dat_caaaff_idx"
            ),
        ),
    ]
