# Generated by Django 6.0.4 on 2026-04-26 06:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhelpedLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("NATURAL", "Natural"), ("C_SECTION", "C-Section")],
                        max_length=20,
                    ),
                ),
                ("alive_count", models.PositiveIntegerField(default=0)),
                ("stillborn_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whelping_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whelping_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "whelped_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhelpedPup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=50)),
                (
                    "birth_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Birth weight in kg",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pups",
                        to="operations.whelpedlog",
                    ),
                ),
            ],
            options={
                "db_table": "whelped_pups",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HealthObsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LIMPING", "Limping"),
                            ("SKIN", "Skin Issue"),
                            ("NOT_EATING", "Not Eating"),
                            ("EYE_EAR", "Eye/Ear Issue"),
                            ("INJURY", "Injury"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("photos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_obs_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_obs_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "health_obs_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="health_obs__dog_id_59b2da_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InHeatLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "draminski_reading",
                    models.IntegerField(
                        help_text="Draminski DOD2 conductivity reading",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "mating_window",
                    models.CharField(
                        choices=[
                            ("EARLY", "Early"),
                            ("RISING", "Rising"),
                            ("FAST", "Fast"),
                            ("PEAK", "Peak"),
                            ("MATE_NOW", "MATE NOW"),
                        ],
                        help_text="Calculated mating window based on thresholds",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heat_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "in_heat_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="in_heat_log_dog_id_94b251_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MatedLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("NATURAL", "Natural"), ("ASSISTED", "Assisted")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mating_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mating_logs",
                        to="operations.dog",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        help_text="Primary sire",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire_mating_logs",
                        to="operations.dog",
                    ),
                ),
                (
                    "sire2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional second sire for dual-sire mating",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sire2_mating_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "mated_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="mated_logs_dog_id_f9ab91_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotReadyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date when dog will be ready",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="not_ready_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="not_ready_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "not_ready_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="not_ready_l_dog_id_3ac6d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NursingFlagLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[("MUM", "Mum Problems"), ("PUP", "Pup Problems")],
                        max_length=20,
                    ),
                ),
                (
                    "pup_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional pup number for pup-specific issues",
                        null=True,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("NO_MILK", "Not Producing Milk"),
                            ("REJECTING_PUP", "Rejecting Pup"),
                            ("PUP_NOT_FEEDING", "Pup Not Feeding"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("photos", models.JSONField(blank=True, default=list)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("SERIOUS", "Serious - Requires Immediate Attention"),
                            ("MONITORING", "Monitoring"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nursing_flag_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nursing_flag_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "nursing_flag_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="nursing_fla_dog_id_614216_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="nursing_fla_severit_dda7d1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weight_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_logs",
                        to="operations.dog",
                    ),
                ),
            ],
            options={
                "db_table": "weight_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dog", "created_at"],
                        name="weight_logs_dog_id_d13ef9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="whelpedlog",
            index=models.Index(
                fields=["dog", "created_at"], name="whelped_log_dog_id_a69428_idx"
            ),
        ),
    ]
