# Generated by Django 6.0.4 on 2026-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_add_follow_up_to_health_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="colour",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="dog",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dog",
            name="unit",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
    ]
