# Generated by Django 6.0.4 on 2026-05-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_change_dogclosure_entity_to_protect"),
        ("operations", "0004_add_default_empty_to_colour_unit_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="whelpedpup",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="whelped_pups",
                to="core.entity",
            ),
        ),
    ]
