# Generated by Django 6.0.4 on 2026-04-24 21:12

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_entity_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="entity",
            name="code",
            field=models.CharField(
                choices=[
                    ("HOLDINGS", "Holdings"),
                    ("KATONG", "Katong"),
                    ("THOMSON", "Thomson"),
                ],
                default="HOLDINGS",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.09,
                help_text="GST rate as decimal (e.g., 0.09 for 9%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                help_text="User's primary entity for data scoping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                to="core.entity",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="pdpa_consent",
            field=models.BooleanField(
                default=False, help_text="User has consented to PDPA terms"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pdpa_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("management", "Management"),
                    ("admin", "Admin"),
                    ("sales", "Sales"),
                    ("ground", "Ground"),
                    ("vet", "Vet"),
                ],
                default="ground",
                help_text="User's primary role for RBAC",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("export", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="EntityMembership",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "created_at"], name="audit_logs_actor_i_5bd818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="audit_logs_action_391715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="audit_logs_resourc_bda8a6_idx",
            ),
        ),
    ]
