# Generated by Django 6.0.4 on 2026-05-06 04:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.09"),
                help_text="GST rate as decimal (e.g., 0.09 for 9%)",
                max_digits=5,
            ),
        ),
    ]
