# Generated by Django 6.0.4 on 2026-05-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_change_dogclosure_entity_to_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="avs_license_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="entity",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
