# Generated by Django 6.0.4 on 2026-04-29 12:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        ("sales", "0002_add_timestamps_and_signature_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quarter", models.CharField(db_index=True, max_length=7)),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_gst", models.DecimalField(decimal_places=2, max_digits=12)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_reports",
                        to="core.entity",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_gst_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-quarter", "-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "quarter", "generated_at"],
                        name="finance_gst_entity__77ec3d_idx",
                    )
                ],
                "unique_together": {("entity", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="IntercompanyTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intercompany_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="core.entity",
                    ),
                ),
                (
                    "to_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_entity", "date"],
                        name="finance_int_from_en_d666ad_idx",
                    ),
                    models.Index(
                        fields=["to_entity", "date"],
                        name="finance_int_to_enti_256532_idx",
                    ),
                    models.Index(
                        fields=["date", "created_at"],
                        name="finance_int_date_ba5ca2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PNLSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cogs", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expenses", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net", models.DecimalField(decimal_places=2, max_digits=12)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pnl_snapshots",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "indexes": [
                    models.Index(
                        fields=["entity", "month", "generated_at"],
                        name="finance_pnl_entity__8ffcd7_idx",
                    ),
                    models.Index(
                        fields=["month", "net"], name="finance_pnl_month_0504b8_idx"
                    ),
                ],
                "unique_together": {("entity", "month")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                            ("TRANSFER", "Transfer"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gst_component",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("VET", "Veterinary"),
                            ("MARKETING", "Marketing"),
                            ("OPERATIONS", "Operations"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.entity",
                    ),
                ),
                (
                    "source_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="sales.salesagreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "date", "type"],
                        name="finance_tra_entity__936995_idx",
                    ),
                    models.Index(
                        fields=["entity", "category", "date"],
                        name="finance_tra_entity__5adcdd_idx",
                    ),
                    models.Index(
                        fields=["date", "type", "category"],
                        name="finance_tra_date_54fcbc_idx",
                    ),
                ],
            },
        ),
    ]
