# Generated by Django 6.0.4 on 2026-05-07 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_change_on_delete_to_protect"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gstreport",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gst_reports",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="gstreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_gst_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="intercompanytransfer",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intercompany_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="intercompanytransfer",
            name="from_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_out",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="intercompanytransfer",
            name="to_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_in",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="pnlsnapshot",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pnl_snapshots",
                to="core.entity",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.entity",
            ),
        ),
    ]
