# Generated by Django 6.0.4 on 2026-04-29 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nric", models.CharField(blank=True, db_index=True, max_length=20)),
                ("mobile", models.CharField(db_index=True, max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "housing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HDB", "HDB"),
                            ("CONDO", "Condominium"),
                            ("LANDED", "Landed Property"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pdpa_consent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Customer has opted in to marketing communications",
                    ),
                ),
                ("pdpa_consent_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers_customer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("blast_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("WA", "WhatsApp")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("BOUNCED", "Bounced"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "message_preview",
                    models.TextField(
                        help_text="First 200 characters of message", max_length=200
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Resend message ID or WA message ID",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communication_logs",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Log",
                "verbose_name_plural": "Communication Logs",
                "db_table": "customers_communication_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "filters_json",
                    models.JSONField(
                        default=dict,
                        help_text="JSON filters: breed, entity, pdpa, date_range, housing_type",
                    ),
                ),
                (
                    "customer_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Cached count of matching customers"
                    ),
                ),
                ("count_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = all entities (management only)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "db_table": "customers_segment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["entity", "pdpa_consent"], name="customers_c_entity__ee7532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["housing_type"], name="customers_c_housing_46e913_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_c_name_f018e2_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["customer", "created_at"], name="customers_c_custome_3be5e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["campaign_id"], name="customers_c_campaig_915923_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["blast_id"], name="customers_c_blast_i_168859_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["channel", "status"], name="customers_c_channel_30cab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segment",
            index=models.Index(
                fields=["entity", "created_at"], name="customers_s_entity__c6829c_idx"
            ),
        ),
    ]
