# Generated by Django 6.0.4 on 2026-05-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_add_null_to_customer_mobile"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE customers_customer SET mobile = NULL WHERE mobile = '';",
            reverse_sql="UPDATE customers_customer SET mobile = '' WHERE mobile IS NULL;",
        ),
    ]
