# Generated by Django 6.0.4 on 2026-04-28 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        ("operations", "0002_add_ground_log_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B2C", "Business to Consumer"),
                            ("B2B", "Business to Business"),
                            ("REHOME", "Rehoming"),
                        ],
                        default="B2C",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SIGNED", "Signed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "buyer_nric",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="NRIC/FIN"
                    ),
                ),
                ("buyer_mobile", models.CharField(max_length=15)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_address", models.TextField()),
                (
                    "buyer_housing_type",
                    models.CharField(
                        choices=[
                            ("HDB", "HDB"),
                            ("CONDO", "Condominium"),
                            ("LANDED", "Landed Property"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("pdpa_consent", models.BooleanField(default=False)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gst_component",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("PAYNOW", "PayNow"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("INSTALLMENT", "Installment"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("special_conditions", models.TextField(blank=True)),
                ("pdf_hash", models.CharField(blank=True, max_length=64)),
                ("pdf_url", models.URLField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_agreements",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "db_table": "sales_agreements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AVSTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buyer_mobile", models.CharField(max_length=15)),
                ("token", models.CharField(db_index=True, max_length=36, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("COMPLETED", "Completed"),
                            ("ESCALATED", "Escalated"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avs_transfers",
                        to="operations.dog",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avs_transfers",
                        to="sales.salesagreement",
                    ),
                ),
            ],
            options={
                "db_table": "sales_avs_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgreementLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gst_component",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_line_items",
                        to="operations.dog",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="sales.salesagreement",
                    ),
                ),
            ],
            options={
                "db_table": "sales_line_items",
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signer_type",
                    models.CharField(
                        choices=[("SELLER", "Seller"), ("BUYER", "Buyer")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In Person"),
                            ("REMOTE", "Remote"),
                            ("PAPER", "Paper"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {x, y, timestamp} for digital signatures",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("image_url", models.URLField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="sales.salesagreement",
                    ),
                ),
            ],
            options={
                "db_table": "sales_signatures",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TCTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B2C", "Business to Consumer"),
                            ("B2B", "Business to Business"),
                            ("REHOME", "Rehoming"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_tc_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_tc_templates",
                "ordering": ["-version"],
            },
        ),
        migrations.AddIndex(
            model_name="salesagreement",
            index=models.Index(
                fields=["entity", "status", "created_at"],
                name="sales_agree_entity__649e35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesagreement",
            index=models.Index(
                fields=["type", "status"], name="sales_agree_type_01cebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesagreement",
            index=models.Index(
                fields=["buyer_mobile"], name="sales_agree_buyer_m_40fa65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesagreement",
            index=models.Index(
                fields=["created_at"], name="sales_agree_created_c5e827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avstransfer",
            index=models.Index(
                fields=["agreement", "status"], name="sales_avs_t_agreeme_1453dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avstransfer",
            index=models.Index(
                fields=["dog", "status"], name="sales_avs_t_dog_id_e4de08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="avstransfer",
            index=models.Index(fields=["token"], name="sales_avs_t_token_08fe27_idx"),
        ),
        migrations.AddIndex(
            model_name="avstransfer",
            index=models.Index(
                fields=["status", "created_at"], name="sales_avs_t_status_c6694e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementlineitem",
            index=models.Index(
                fields=["agreement", "dog"], name="sales_line__agreeme_a1c922_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agreementlineitem",
            unique_together={("agreement", "dog")},
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(
                fields=["agreement", "signer_type"],
                name="sales_signa_agreeme_ec9ec6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(
                fields=["timestamp"], name="sales_signa_timesta_b27709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tctemplate",
            index=models.Index(
                fields=["type", "version"], name="sales_tc_te_type_7ebf48_idx"
            ),
        ),
    ]
