# Generated by Django 6.0.4 on 2026-04-28 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_managers_remove_user_is_entity_admin_and_more"),
        ("sales", "0002_add_timestamps_and_signature_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        db_index=True, help_text="Quarter format: YYYY-Q#", max_length=7
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gst_component",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gst_ledger_entries",
                        to="core.entity",
                    ),
                ),
                (
                    "source_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gst_ledger_entries",
                        to="sales.salesagreement",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_gst_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "period"],
                        name="compliance__entity__85b4da_idx",
                    ),
                    models.Index(
                        fields=["source_agreement"],
                        name="compliance__source__563d2c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NParksSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of the reporting month"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("mating_sheet_url", models.URLField(blank=True)),
                ("puppy_movement_url", models.URLField(blank=True)),
                ("vet_treatments_url", models.URLField(blank=True)),
                ("puppies_bred_url", models.URLField(blank=True)),
                ("dog_movement_url", models.URLField(blank=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nparks_submissions",
                        to="core.entity",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_nparks_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_nparks_submissions",
                "ordering": ["-month"],
                "indexes": [
                    models.Index(
                        fields=["entity", "status", "month"],
                        name="compliance__entity__3a6fca_idx",
                    ),
                    models.Index(
                        fields=["status", "generated_at"],
                        name="compliance__status_39519f_idx",
                    ),
                ],
                "unique_together": {("entity", "month")},
            },
        ),
        migrations.CreateModel(
            name="PDPAConsentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_id",
                    models.UUIDField(
                        db_index=True, help_text="Customer UUID reference"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("OPT_IN", "Opt In"), ("OPT_OUT", "Opt Out")],
                        max_length=10,
                    ),
                ),
                ("previous_state", models.BooleanField()),
                ("new_state", models.BooleanField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdpa_consent_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_pdpa_consent_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_id", "created_at"],
                        name="compliance__custome_576cbb_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="compliance__action_105dc1_idx",
                    ),
                ],
            },
        ),
    ]
