# Generated by Django 6.0.4 on 2026-05-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nparkssubmission",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Soft delete flag - False means deleted"
            ),
        ),
    ]
